activation: relu
batch_size: 64
dataset: Drugs
dropout: 0.5
hidden_dim: 64
learning_rate: 0.001
max_atomic_num: 2.0
max_num_conformers: 19
max_num_molecules: null
multitask: false
num_epochs: 2000
patience: 200
seed: 123
target: ip
train_ratio: 0.7
unique_variables: 1
valid_ratio: 0.1
weight_decay: 0.0001
