activation: relu
batch_size: 256
dataset: BDE
device: cuda:0
dropout: 0.5
hidden_dim: 128
learning_rate: 0.001
max_atomic_num: 79
max_num_conformers: 20
max_num_molecules: null
num_epochs: 2000
patience: 200
scheduler: null
seed: 123
target: BindingEnergy
train_ratio: 0.7
unique_variables: 2
valid_ratio: 0.1
weight_decay: 0.0001
