activation: relu
batch_size: 64
dataset: tmQMg
dropout: 0.5
hidden_dim: 128
learning_rate: 0.001
max_atomic_num: 80
max_num_conformers: 20
max_num_molecules: null
multitask: false
num_epochs: 2000
patience: 50
seed: 123
target: tzvp_dipole_moment
train_ratio: 0.7
unique_variables: 1
valid_ratio: 0.1
weight_decay: 0.0001
